// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GoogleGames
{
        public const string achievement_shopping_spree = "CgkIgbS3o6AFEAIQDA"; // <GPGSID>
        public const string achievement_youre_player = "CgkIgbS3o6AFEAIQCQ"; // <GPGSID>
        public const string achievement_thats_my = "CgkIgbS3o6AFEAIQBQ"; // <GPGSID>
        public const string achievement_music_king = "CgkIgbS3o6AFEAIQCw"; // <GPGSID>
        public const string achievement_hardcore = "CgkIgbS3o6AFEAIQBg"; // <GPGSID>
        public const string achievement_uff_ended = "CgkIgbS3o6AFEAIQAw"; // <GPGSID>
        public const string achievement_new_map_new_life = "CgkIgbS3o6AFEAIQBA"; // <GPGSID>
        public const string achievement_made_in_china = "CgkIgbS3o6AFEAIQDg"; // <GPGSID>
        public const string achievement_dj = "CgkIgbS3o6AFEAIQCg"; // <GPGSID>
        public const string achievement_blinked_and_thats_it = "CgkIgbS3o6AFEAIQAQ"; // <GPGSID>
        public const string achievement_terrible = "CgkIgbS3o6AFEAIQDQ"; // <GPGSID>
        public const string leaderboard_kings_of_the_beats = "CgkIgbS3o6AFEAIQAg"; // <GPGSID>

}

